export enum CardRarity {
  COMMON = "COMMON",
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  PROMO = "PROMO",
  DOUBLE_RARE = "DOUBLE_RARE",
  ULTRA_RARE = "ULTRA_RARE",
  ILLUSTRATION_RARE = "ILLUSTRATION_RARE",
  SPECIAL_ILLUSTRATION_RARE = "SPECIAL_ILLUSTRATION_RARE",
  HYPER_RARE = "HYPER_RARE",
}
